FROM betrybe/figtrybe-artify:latest
# lembrar de colocar a versão
ENTRYPOINT [ "node" , "app.js" ]
CMD [ "#VQV Trybe" ]

# código para gerar a imagem
# docker image build ./ -t figtrybe-artify
# docker container run --rm figtrybe-artify
# no código acima, posso adicionar um outro texto na imagem
# -f roda com a fonte Ghost, que é a q eu quero 